2019-07-22 08:38:25,909 - [INFO] - [msg]开始执行用例 - test_03_recharge.py - 23
2019-07-22 08:38:27,069 - [ERROR] - [msg]测试正常登录, 执行结果：Fail具体异常为：测试正常登录 :: 10001 != {"status":0,"code":"20111","data":null,"msg":"用户名或密码错误"} - test_03_recharge.py - 52
2019-07-22 08:38:28,024 - [ERROR] - [msg]测试充值成功, 执行结果：Fail具体异常为：测试充值成功 :: 10001 != {"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"} - test_03_recharge.py - 52
2019-07-22 08:38:28,686 - [ERROR] - [msg]测试充值失败，金额为空, 执行结果：Fail具体异常为：测试充值失败，金额为空 :: 20103 != {"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"} - test_03_recharge.py - 52
2019-07-22 08:38:29,422 - [ERROR] - [msg]测试充值失败，对应会员不存在, 执行结果：Fail具体异常为：测试充值失败，对应会员不存在 :: 20104 != {"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"} - test_03_recharge.py - 52
2019-07-22 08:38:30,112 - [ERROR] - [msg]测试充值失败，手机格式不对, 执行结果：Fail具体异常为：测试充值失败，手机格式不对 :: 20109 != {"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"} - test_03_recharge.py - 52
2019-07-22 08:38:30,893 - [ERROR] - [msg]测试充值失败，金额为空, 执行结果：Fail具体异常为：测试充值失败，金额为空 :: 20115 != {"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"} - test_03_recharge.py - 52
2019-07-22 08:38:31,691 - [ERROR] - [msg]测试充值失败，金额小数为4, 执行结果：Fail具体异常为：测试充值失败，金额小数为4 :: 20116 != {"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"} - test_03_recharge.py - 52
2019-07-22 08:38:32,475 - [ERROR] - [msg]测试充值失败，金额大于50万, 执行结果：Fail具体异常为：测试充值失败，金额大于50万 :: 20117 != {"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"} - test_03_recharge.py - 52
2019-07-22 08:38:33,358 - [ERROR] - [msg]测试充值失败，金额为字母, 执行结果：Fail具体异常为：测试充值失败，金额为字母 :: 20118 != {"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"} - test_03_recharge.py - 52
2019-07-22 08:38:33,359 - [INFO] - [msg]用例执行结束 - test_03_recharge.py - 28
