2019-07-22 08:34:30,310 - [INFO] - [msg]开始执行用例 - test_01_register.py - 25
2019-07-22 08:34:34,254 - [INFO] - [msg]用例执行结束 - test_01_register.py - 31
2019-07-22 08:34:34,255 - [INFO] - [msg]开始执行用例 - test_02_login.py - 25
2019-07-22 08:34:35,597 - [INFO] - [msg]用例执行结束 - test_02_login.py - 30
2019-07-22 08:34:35,597 - [INFO] - [msg]开始执行用例 - test_03_recharge.py - 23
2019-07-22 08:34:38,179 - [ERROR] - [msg]测试充值失败，金额为空, 执行结果：Fail具体异常为：20115 != '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试充值失败，金额为空 - test_03_recharge.py - 52
2019-07-22 08:34:38,648 - [ERROR] - [msg]测试充值失败，金额小数为4, 执行结果：Fail具体异常为：20116 != '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试充值失败，金额小数为4 - test_03_recharge.py - 52
2019-07-22 08:34:39,210 - [ERROR] - [msg]测试充值失败，金额大于50万, 执行结果：Fail具体异常为：20117 != '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试充值失败，金额大于50万 - test_03_recharge.py - 52
2019-07-22 08:34:39,796 - [ERROR] - [msg]测试充值失败，金额为字母, 执行结果：Fail具体异常为：20118 != '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试充值失败，金额为字母 - test_03_recharge.py - 52
2019-07-22 08:34:39,796 - [INFO] - [msg]用例执行结束 - test_03_recharge.py - 28
2019-07-22 08:34:39,948 - [INFO] - [msg]开始执行用例 - test_04_add.py - 28
2019-07-22 08:34:40,142 - [INFO] - [msg]用例执行结束 - test_04_add.py - 35
2019-07-22 08:34:40,303 - [INFO] - [msg]开始执行用例 - test_05_invest.py - 29
2019-07-22 08:34:40,305 - [INFO] - [msg]用例执行结束 - test_05_invest.py - 36
